version: '2.2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    depends_on:
      - elastic-logs
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elastic-logs:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./elk/deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - elk_network

  elastic-logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    logging:
      driver: none
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elastic-logs
    networks:
      - elk_network
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic-logs:9200"]'
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.3.2
  #   entrypoint: "filebeat -e -strict.perms=false"
  #   volumes:
  #     - /tmp/logs/nginx:/var/log/nginx:ro
  #     - ./elk/deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #   networks:
  #     - elk_network
  #   depends_on:
  #     - logstash
  #     - elastic-logs
  #     - kibana

networks:
  elk_network:
    name: elk_network
    driver: bridge
