filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true

# output.logstash:
#   enabled: true
#   hosts: ["logstash:5045"] 

output.elasticsearch:
  hosts: ["https://elastic-logs:9200"]
  # для эластика на проде
  # username: "filebeat_writer"
  # password: "YOUR_PASSWORD"