# Generated by Django 4.0 on 2022-08-18 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('template', models.TextField(verbose_name='template')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'db_table': 'content"."emailtemplate',
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationTask',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('priority_level', models.CharField(choices=[('low', 'low'), ('mid', 'mid'), ('high', 'high')], max_length=4, verbose_name='priority level')),
                ('status', models.TextField(choices=[('created', 'created'), ('in_process', 'in process'), ('delivered', 'delivered')], default='created', verbose_name='status')),
                ('scheduled_datetime', models.DateTimeField(auto_now=True, verbose_name='scheduled timestamp')),
                ('sending_datetime', models.DateTimeField(blank=True, null=True, verbose_name='sending timestamp')),
                ('user_roles', models.TextField(verbose_name='user roles')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.emailtemplate')),
            ],
            options={
                'verbose_name': 'email notification task',
                'verbose_name_plural': 'email notification tasks',
                'db_table': 'content"."emailnotificationtask',
            },
        ),
    ]
