name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Current py version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy wemake-python-styleguide lxml flake8-html

      - name: Create linter report directory
        run: mkdir -p reports/notifications/wemake-python-styleguide/

      - name: Lint with wemake-python-styleguide
        run: flake8 notifications --exit-zero --format=html --htmldir=reports/notifications/wemake-python-styleguide/

      - name: Check typing with mypy
        run: mypy --html-report reports/notifications/mypy/ ./notifications || true

      - name: Get reports
        uses: actions/upload-artifact@v3
        with:
          name: html_reports
          path: reports/

      - name: Telegram notifications
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TelegramBotToken }}
          chatId: ${{ secrets.TelegramChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
